name: couldai_user_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Localization support
  flutter_localizations:
    sdk: flutter
    
  # Internationalization utilities
  intl: ^0.19.0
    
  # Web URL strategy
  url_strategy: ^0.2.0

  # Supabase for Backend
  supabase_flutter: ^2.8.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
